version: 2
updates:

  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Android
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
